overwrite: true
schema: './schema.graphql'
documents: 'apps/**/*.graphql'
generates:
  apps/jira-clone/src/app/core/graphql/service/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-apollo-angular'
  ./graphql.schema.json:
    plugins:
      - 'introspection'
